### ISSUE TITLE
What's the rule of routing?

### ISSUE THREAD

**Issue by kynwu** [richardgirges/paycryptor#1]
thanks for this nice package...
and I'm curious about how do you do the judge of routing?
any further information?

**Comment by richardgirges** [comment]
Heya, 

Can you elaborate on what you mean by routing? The route of the cert path??

**Comment by kynwu** [comment]
Sorry for not making it clear.
I mean "Validate U.S. Routing Numbers" section.
it seems to have some kind of rules to do this.

**Comment by richardgirges** [comment]
Ahh yes. I am validating against the MICR Routing Number Format.  This Wikipedia article shows the algorithm and rules for validating against US Routing Numbers: https://en.wikipedia.org/wiki/Routing_transit_number#MICR_Routing_number_format

I've implemented that logic in the JavaScript to validate US routing numbers with the `validateRouting()` function.

**Comment by kynwu** [comment]
Thanks again for your reply.
Does "Validate U.S. Routing Numbers" validate the routing number of credit cards or debit cards?
I ask this because I saw some article say that a credit card / debit card doesn't have a routing number....
but a check can have a routing number...is this right?

**Comment by richardgirges** [comment]
No problem.

Yeah there are no routing numbers for credit cards and debit cards.  Only for checking accounts. The `validateRouting()` function is meant to only validate against U.S. routing numbers that are typically used for U.S. checking accounts.
